- index.js
Fix for https://github.com/abramenal/cypress-file-upload/issues/12
> feat: make command then-able

- .eslintrc
- README.md
- example/cypress/integration/input.spec.js
- example/cypress/integration/simple.js
- example/src/components/app.jsx
- example/src/components/upload-input/index.jsx
- index.d.ts
- index.js
- package.json
Contains breaking changes in command public API.
Also fixes #15
> Add simple upload

- package.json
> Updates engine dependency to >=8.2.1

- example/cypress/integration/dropzone.spec.js
- example/cypress/integration/input.spec.js
- example/src/components/app.jsx
Problem: If `cy.upload`, not select file, test passed
Add real check for upload command
> Tests: update example code and test, add view file name after select file and test it

- example/README.md
- example/cypress/support/commands.js
> Example app: replace import cypress-file-upload on local

- index.js
- remove unimportant command (window, wrap)
- add cypress custom comand upload
**before**:
**after**:
input:
drop: 
on click:
> Add cypress log command

- src/helpers/getFileBlob.js
- src/helpers/getFileBlobAsync.js
- src/upload.js
> bugfix: resolve async file blob conversion

- src/helpers/getValidEncoding.js
> Add PDF support

- README.md
- src/helpers/ensureDefaults.js
- src/helpers/index.js
- src/upload.js
> feat: make processingOptions parameter optional with defaults

- README.md
> docs: update caveats with reading file content recipe

- src/helpers/ensureDefaults.js
> fix: let processing options be optional

- README.md
- src/error.js
- src/handlers/handleDragDrop.js
- src/upload.js
- src/validators/validateOptions.js
Added events option in drag-n-drop mode.
Related to #120.
> Define custom trigger events 

- src/handlers/handleDragDrop.js
> feat: support FileList native API

- src/validators/validateSubject.js
> feat: support button as valid DOM subject

- src/handlers/handleDragDrop.js
- src/handlers/handleInput.js
- src/handlers/handleShadowDragDrop.js
- src/handlers/handleShadowInput.js
Closes #138 
Also contains f138143f87d781372a8ad80aa404c3c105668a16 which I occasionaly committed in a wrong way.
> feat: use application's global object instead of cypress runner window ones 

- package.json
- recipes/angularjs-ng-file-upload/package.json
- recipes/react-dropzone/package.json
- recipes/react-html5-input/package.json
- recipes/shadow-dom-native/.gitignore
- recipes/shadow-dom-native/cypress/integration/file-input.spec.js
- recipes/shadow-dom-native/package.json
- src/helpers/isManualEventTrigger.js
> feat: add cross-browser support

- recipes/react-dropzone/cypress/integration/dropzone.spec.js
- recipes/react-dropzone/src/components/app.jsx
- recipes/react-dropzone/src/components/upload-dropzone/index.jsx
> docs: add case for hidden dropzone usage

- types/index.d.ts
> feat: update types for es6+ targets support

- README.md
- recipes/react-html5-input/cypress/integration/mimeTypes.spec.js
- src/attachFile.js
- src/error.js
- src/helpers/getFixtureInfo.js
- src/validators/validateFixture.js
- types/index.d.ts
> feat: add ability to explicitly set mime type

- src/helpers/getFixtureInfo.js
Related to changes in #184 
cc @jdcl32
> feat: fix auto filename assignment

- src/helpers/attachFileToElement.js
> feat: avoid throwing error if subject element disappears

- lib/file/getFileBlobAsync.js
> fix: load json content

- README.md
I just made this change and it seems to be working.
> Added Typescript instructions

- README.md
README updates
Closes #242
Closes #149
Closes #209
> docs: add more extensive integration guide

- recipes/angularjs-ng-file-upload/package-lock.json
- recipes/angularjs-ng-file-upload/package.json
- recipes/react-dropzone/package-lock.json
- recipes/react-dropzone/package.json
- recipes/react-html5-input/package-lock.json
- recipes/react-html5-input/package.json
- recipes/shadow-dom-native/package-lock.json
- recipes/shadow-dom-native/package.json
Check if plugin works with latest `cypress@6.2.1`
Closes #239
> chore(recipes): upgrade to latest cypress version

- README.md
_Please provide here description of how this PR changes the codebase and the
application and/or what bugs it fixes._
_You might use keyword combinations like"Closes #1" to link issues or other related PRs_
> docs: Update example to use `.attachFile` rather than `.upload`

- .github/workflows/build.yml
- lib/file/getFileMimeType.js
- package-lock.json
- package.json
- recipes/angularjs-ng-file-upload/cypress/support/commands.js
- recipes/react-dropzone/cypress/support/commands.js
- recipes/react-html5-input/cypress/support/commands.js
- recipes/shadow-dom-native/cypress/support/commands.js
- Set correct build target
- Include `mime` dependency into bundle
- Run e2e tests against bundled code, not sources (ensures build is actually working)
Closes #250
Closes #239
> chore: fix bundle configuration

- src/helpers/attachFileToElement.ts
_Please provide here description of how this PR changes the codebase and the
application and/or what bugs it fixes._
_You might use keyword combinations like"Closes #1" to link issues or other related PRs_
Closes #320
> feat: fix dropzone behavior in firefox

- lib/file/getFileEncoding.ts
_Please provide here description of how this PR changes the codebase and the
application and/or what bugs it fixes._
_You might use keyword combinations like"Closes #1" to link issues or other related PRs_
Closes #238
> feat: use base64 encoding for pdf files
