abramenal/cypress-file-upload

index.d.ts, package.json
This allows Typescript users to use `cy.upload` without issues and to have autocomplete for it.
=> Add Typescript typedefs for the `upload` command

src/helpers/getValidEncoding.js
PDF files can contain non ASCII characters, which will result in an `InvalidCharacterError` when the base64 gets decoded using `atob`. I'd therefore propose utf8 as the preset for PDFs instead.
=> fix: use utf8 as default encoding for PDF files

src/helpers/getValidEncoding.js
Closes #66 
FYI @xiaomeidan in v3.1.1 it will work without setting `encoding` explicitly, like:
```
cy.fixture('user.vcf').then(fileContent => {
cy.get('input[type="file"]').upload(
{ fileContent, fileName: 'user.vcf', mimeType: 'text/vcard' },
{ subjectType: 'input' },
);
});
```
=> Add VCF file support

index.d.ts
Specified types of `FileData.endocing` and `FileProcessingOptions.subjectType` to avoid mistakes and get autocomplete suggestions.
=> Specified types for encoding and subjectType

README.md
It took me quite some time to find what exact value to pass through there (turned out I need lowercase).
This would help people find the right string value faster.
=> Add link to allowed encodings to README

index.d.ts
Hi :wave: Thanks for the superb lib, it really saved my bacon 😊 
Seems like this options object is optional so we can make it optional in the typings too.
=> Make processingOpts optional in typings

src/handlers/handleDragDrop.js
In our codebase, we rely on `dragenter` occurring before `drop`, and that's also the cycle that would be expected out of an actual user. This PR adds a `dragenter` event before it triggers `drop`.
=> Trigger dragenter before dragover

README.md, index.d.ts, recipes/shadow-dom-native/cypress/integration/file-input.spec.js, src/error.js, src/upload.js, src/validators/validateFiles.js, src/validators/validateOptions.js
Attempting to upload an empty file throws an error.
To be able to upload an empty file.
cy.get('[data-cy="file-input"]').upload({ '', fileName: 'empty.txt', mimeType: 'text/plain' });
cypress-file-upload 3.4.0
=> Allow empty fileContent

README.md, lib/file/getFileBlobAsync.js, lib/file/getFileContent.js, lib/file/index.js, src/attachFile.js, src/error.js, src/helpers/getFixtureInfo.js, src/validators/validateFixture.js, types/index.d.ts
@abramenal This PR fix issues:
* https://github.com/abramenal/cypress-file-upload/issues/180
* https://github.com/abramenal/cypress-file-upload/issues/174
It also add back the ability to provide a fileContent that will allow a work around for: https://github.com/abramenal/cypress-file-upload/issues/175
=> fix: v4 regressions

src/attachFile.js, src/helpers/attachFileToElement.js, types/index.d.ts
Fix for this issue: https://github.com/abramenal/cypress-file-upload/issues/181
The problem was when creating the DataTranfer object we did not use the constructor from the window that host the site being tested and It was failing the validation.
=> properly build data transfer object

README.md
Change the link in the readme to point to the right `constants.js` about available encodings options.
=> Fix readme link to constants for encodings options

README.md
Hello, Team! 
This PR about fixing typo inside README.file
During my last installation, I found this issue when I was doing copy/paste of this block
```
const special = 'file.spss';
cy.fixtures(special, 'binary')
.then(Cypress.Blob.binaryStringToBlob)
.then((fileContent) => {
cy.get('[data-cy="file-input"]').attachFile({ fileContent, filePath: special, encoding: 'utf-8' });
})
```
as you can see `fixtures` word is in plural form but should be in single according to the cypress [documentation](https://docs.cypress.io/api/commands/fixture.html#Syntax) and 
and inside the library
So it is the only way to make it work to use single form `fixture`
@abramenal  thank you in advance for approving!
Best 
Zhenja
=> [Typo] in README.md `fixtures` -> `fixture`

lib/file/getFileBlobAsync.js, package.json
Wraps return value of `Cypress.Blob.base64StringToBlob()` in a `Cypress.Promise.resolve`, which will allow us to treat it as a Promise no matter what. If it's already a Promise, as it was in Cypress <=4, this will be also be compatible. 
Fixes #214
=> Update Blob use to be compatible with Cypress 5.0

lib/file/common.js, lib/file/getFileBlobAsync.js, lib/file/getFileContent.js
Use `wrapBlob` in `getFileContent` to avoid cypress 5.0 error: `binaryStringToBlob() no longer returns a Promise. Update the use of binaryStringToBlob() to expect a returned Blob`
=> fix: delete fileContent.then in getFileContent to avoid error from cypress 5.0

README.md
...because I thought that, in the first example, the JSON file was metadata about the file to upload, and wasted a lot of time because of this misunderstanding.
I understood thanks to this StackOverflow answer: https://stackoverflow.com/a/62204487/592254
=> fix(docs): Make it clear that the fixture file can be any file

types/index.d.ts
The documentation states
> when providing fileContent is possible to ignore filePath but fileName and mime type must be provided
The previous type coverage didn't allow for that.
=> Allow fileContent without filePath in types

README.md
This solves the issue of intellisense not recognising the `cypress-file-upload` methods on the `cypress`object.
Issue/solution described here: https://github.com/abramenal/cypress-file-upload/issues/202#issuecomment-690093574
=> Update README to include reference to  "cypress-file-upload" in .tsconfig setup

types/index.d.ts
Fix issue with type interface. Add exact type for encoding.
Closes #224
=> feat: improve types

recipes/react-html5-input/cypress/integration/repeated.spec.js, src/helpers/attachFileToElement.js
Do not preserve existing files.
This functionality was making sense when doing chaining calls, but now it is redundant. More than that, it is different from user may experience when doing same actions manually.
Closes #264
=> feat: do not preserve existing files

README.md, lib/file/getFileBlobAsync.js, lib/file/resolveFile.js, src/error.js, src/helpers/getFixtureInfo.js, src/validators/validateFixture.js, types/index.d.ts
This allows you to pass a lastModified attribute to be used for the file.  This is helpful for testing the uploading of duplicate files so they can have the same lastModified and fingerprint.
Closes #277
=> allow setting a files lastModified property

.github/workflows/build.yml
Long time ago Firefox tests were disabled on CI, which makes FF testing manual only (read "impossible"). This PR addresses this CI issue
Also this PR removes `fail-fast` behavior, so failure in a single matrix step won't fail all other in-progress steps.
#294
=> chore: enable Firefox testing

lib/browser/index.js, lib/browser/isBrowserFirefox.js, src/helpers/attachFileToElement.js
#290 broke Firefox compatibility. This PR adds a specific check to see if the Cypress runner broswer is Firefox to manually add `'change'` into the drag'n'drop list of events because its presence was casing duplication for Chrome (see #276). 
Draft PR instead of ready for review because we should probably add tests that try and repro some of these issues (either Chrome duplication, or Firefox upload functionality broken) so that we don't play whack-a-mole with patch PRs. 
Closes #293
=> Fix Firefox Drag'n'Drop Functionality

lib/file/getFileBlobAsync.js, lib/file/getFileEncoding.js, lib/file/getFileExt.js, lib/file/getFileMimeType.js, lib/file/getFileName.js, lib/file/index.js, src/helpers/getFixtureInfo.js
Replace Node.js module imports with own implementation.
Closes #301
Closes #250
Closes #236
=> refactor: replace node.js module imports with own implementations

types/index.d.ts
Fixes #305
I admittedly don't understand what side-effect removing this line will have. I've only worked with types in TypeScript projects where the declarations file are generated by the TypeScript compiler rather than those written manually such as this. However, I don't think we need these types pulled in as a dependency here because you're not even using them - so they are just added to the global namespace without really adding any value.
Alos, Cypress users using TypeScript will already have cypress types pulled in with their tsconfig file, e.g. `"types": ["cypress"],`.
_Please provide here description of how this PR changes the codebase and the
application and/or what bugs it fixes._
_You might use keyword combinations like"Closes #1" to link issues or other related PRs_
=> Remove cypress types reference

types/index.d.ts
When file extension is json, file content needs to be an object and not Blob.  
You can see it there:   
https://github.com/abramenal/cypress-file-upload/blob/45ae45cc97c4833e594285c9631208246e27413c/lib/file/getFileBlobAsync.js#L27
So I changed the contentFile type to be a Blob or object
=> Fix fileContent type
